mrm:
  mrm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - base_link__link_01
      - link1_link2
      - link2_link3
      - link3_link4
      - link4_link5
      - link5_link6

  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - gripper_right
      - gripper_left
    gains:
      gripper_right:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}
      gripper_left:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}

